### ISSUE TITLE
Fix board display in Chrome for Phone

### ISSUE THREAD

**Issue by Dohbedoh** [ChessCorp/chess-board#9]
The board is not displayed consistently in Samsung galaxy S3 mini. Drag & Drop as well as 2 click move are difficult to use.

Landscape:
![s3mini-landscape](https://cloud.githubusercontent.com/assets/6858329/9456445/13ec392e-4b1b-11e5-9450-74021d046b0c.png)

Portrait:
![s3mini-portrait](https://cloud.githubusercontent.com/assets/6858329/9456446/15637902-4b1b-11e5-9700-a00850042ff2.png)

**Comment by alcibiade** [comment]
This is probably related to #5 as the board should not allow cells to be scaled down horizontally. They should instead scale down along with the pieces.
